on:
  rss:
    url: https://www.animenewsnetwork.com/news/rss.xml?ann-edition=fr
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{http://mangafrr.blogspot.com/}}
          contentSnippet: ${{http://mangafrr.blogspot.com/}}
          link: ${{http://mangafrr.blogspot.com/}}
