on:
  rss:
    url: https://www.animenewsnetwork.com/news/rss.xml?ann-edition=fr
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: https://mangasfrr.blogspot.com/
          user: ${{secrets.yoyo@gmail.com}}
          password: ${{secrets.yoyo12345}}
          method: POST
          body: |
            {
              "link":"${{on.rss.outputs.link}}", 
              "title": "${{on.rss.outputs.title}}",
              "content":"<<<${{on.rss.outputs.contentSnippet}}>>>"
            }
